# name: Version Testing fastp-minimap2 CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  # derived from https://github.com/actions/example-services/blob/master/.github/workflows/postgres-service.yml
  version-testing:
    runs-on: macos-latest

    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup for conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.9

      - name: Basic dependencies install
        shell: bash -l {0}
        run: |
          conda config --add channels conda-forge
          conda config --add channels bioconda
          conda create --yes -n fastp-minimap2 -c bioconda samtools=1.11 minimap2 fastp python=3.9
          conda activate fastp-minimap2

          samtools_version=`samtools --version`
          minimap2_version=`minimap2 --version`
          fastp_version=$(fastp --version 2>&1)
          if [[ $samtools_version != *"1.11"* ]]; then echo "wrong samtools version", $samtools_version; exit 1; fi
          if [[ $minimap2_version != *"2.24"* ]]; then echo "wrong minimap2 version", $minimap2_version; exit 1; fi
          if [[ $fastp_version != *"0.23.2"* ]]; then echo "wrong fastp version", $fastp_version; exit 1; fi

          # cleaning conda packages to empty some space
          conda deactivate
          conda clean --yes --all

          echo "Untar main files"
          tar zxvf data.tgz

      - name: Building reference database
        shell: bash -l {0}
        env:
          NPROCS: 12
        run: |
          conda activate fastp-minimap2

          echo "Downloading files"
          wget -q ftp://ftp.ncbi.nlm.nih.gov/genomes/Viruses/enterobacteria_phage_phix174_sensu_lato_uid14015/NC_001422.fna
          wget -q https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/009/914/755/GCA_009914755.4_T2T-CHM13v2.0/GCA_009914755.4_T2T-CHM13v2.0_genomic.fna.gz
          gunzip -q GCA_009914755.4_T2T-CHM13v2.0_genomic.fna.gz
          cat GCA_009914755.4_T2T-CHM13v2.0_genomic.fna NC_001422.fna > human-phix.fna

          # build the minimap2 DB
          echo "Building minimap2 database"
          minimap2 -ax sr -t $NPROCS -d human-phix-db.mmi human-phix.fna

          # remove large unneeded files
          rm GCA_009914755.4_T2T-CHM13v2.0_genomic.fna NC_001422.fna human-phix.fna

      - name: Running tests
        shell: bash -l {0}
        run: |
          conda activate fastp-minimap2

          python test_filter_commands.py
