# name: Version Testing fastp-minimap2 CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  # derived from https://github.com/actions/example-services/blob/master/.github/workflows/postgres-service.yml
  main:
    runs-on: ubuntu-latest

    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup for conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.9

      - name: Basic dependencies install
        shell: bash -l {0}
        run: |
          echo "Testing: " $COVER_PACKAGE

          conda config --add channels bioconda
          conda config --add channels conda-forge
          conda create --yes -n fastp-minimap2 -c bioconda minimap2 fastp
          conda activate fastp-minimap2
          conda install samtools

          samtools_version=`samtools --version`
          minimap2_version=`minimap2 --version`
          fastp_version=$(fastp --version 2>&1)
          if [[ $samtools_version != *"1.11"* ]]; then echo "wrong samtools version", $samtools_version; exit 1; fi
          if [[ $minimap2_version != *"2.24"* ]]; then echo "wrong minimap2 version", $minimap2_version; exit 1; fi
          if [[ $fastp_version != *"0.23.2"* ]]; then echo "wrong fastp version", $fastp_version; exit 1; fi

      - name: Building reference database
        shell: bash -l {0}
        env:
          NPROCS: 12
        run: |
          conda activate fastp-minimap2

          wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/001/405/GCF_000001405.39_GRCh38.p13/GCF_000001405.39_GRCh38.p13_genomic.fna.gz
          wget ftp://ftp.ncbi.nlm.nih.gov/genomes/Viruses/enterobacteria_phage_phix174_sensu_lato_uid14015/NC_001422.fna
          gunzip GCF_000001405.39_GRCh38.p13_genomic.fna.gz
          cat GCF_000001405.39_GRCh38.p13_genomic.fna NC_001422.fna > human-phix.fna

          # build the minimap2 DB
          minimap2 -ax sr -t $NPROCS -d human-phix-db.mmi human-phix.fna

          # remove large unneeded files
          rm GCF_000001405.39_GRCh38.p13_genomic.fna
          rm NC_001422.fna
          rm human-phix.fna
